// Real HTTP + Mongo replica-set regression. Never reads .env or an existing application DB.
// Optional browser coverage: BILLSTACK_PLAYWRIGHT_PATH and BILLSTACK_PHASE1_UI=http://127.0.0.1:5184.
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const mongoose = require("mongoose");
const uri = process.env.BILLSTACK_PHASE1_MONGO || "mongodb://127.0.0.1:27029/?replicaSet=rs0";
const parsed = new URL(uri);
if (parsed.hostname !== "127.0.0.1" || parsed.username || parsed.password) throw new Error("Tests require a credential-free loopback MongoDB");
process.env.NODE_ENV = "test";
process.env.JWT_SECRET = crypto.randomBytes(48).toString("hex");
process.env.BILLSTACK_DEPLOYMENT_MODE = "SELF_HOSTED";
process.env.CLIENT_URL = process.env.BILLSTACK_PHASE1_UI || "http://127.0.0.1:5184";
process.env.API_BASE_URL = "http://127.0.0.1:5011";
// Existing unrelated legacy partial indexes use unsupported $ne. Build the indexes exercised here explicitly.
mongoose.set("autoIndex", false);
const Business = require("../src/models/Business");
const User = require("../src/models/User");
const Customer = require("../src/models/Customer");
const Invoice = require("../src/models/Invoice");
const Membership = require("../src/models/BusinessMembership");
const Config = require("../src/models/BusinessModuleConfig");
const { hashPassword, signAccessToken } = require("../src/services/auth.service");
const { buildInvoicePdfDefinition } = require("../src/utils/pdfInvoice");
const pass = message => console.log(`PHASE1 PASS: ${message}`);
let server, browser;
(async () => {
 await mongoose.connect(uri, { dbName: `billstack_phase1_test_${Date.now()}`, serverSelectionTimeoutMS: 10000 });
 assert.equal((await mongoose.connection.db.admin().command({ hello: 1 })).setName, "rs0");
 await Business.createIndexes(); await Membership.createIndexes();
 await Invoice.collection.createIndex({ businessId: 1, invoiceNumber: 1 }, { unique: true });
 await require("../src/models/IntegrationCustomerMapping").createIndexes();
 await require("../src/models/IntegrationHandoff").createIndexes();
 await require("../src/models/Payment").collection.createIndex({ businessId: 1, idempotencyKey: 1 }, { unique: true, partialFilterExpression: { idempotencyKey: { $gt: "" } } });
 const password = crypto.randomBytes(18).toString("hex");
 const toor = await Business.create({ name: "The Office On Rent", slug: `phase1-${Date.now()}`, deploymentMode: "SELF_HOSTED", industry: "Real Estate", onboardingCompleted: true, businessProfile: { industryCode: "REAL_ESTATE", playerTypeCode: "BROKER", businessModel: "SERVICE", onboardingStatus: "COMPLETED", recommendedModules: ["invoices", "customers", "reports", "expenses", "products_services"] }, gstTaxId: "23CGZPB7175E1Z5", gstConfiguration: { enabled: true, gstin: "23CGZPB7175E1Z5", stateCode: "23" }, bankDetails: { accountName: "Test seller", bankName: "Test bank", accountNumber: "test-account" }, invoiceNumbering: { prefix: "TOOR", format: "INV-{YYYY}-{0001}", nextSequence: 1 } });
 const owner = await User.create({ businessId: toor._id, name: "Phase1 Owner", email: "phase1-owner@example.test", password: await hashPassword(password), role: "owner" });
 toor.ownerUserId = owner._id; await toor.save();
 const employee = await User.create({ businessId: toor._id, name: "Phase1 Staff", email: "phase1-staff@example.test", password: await hashPassword(password), role: "staff" });
 const foreign = await Business.create({ name: "Unrelated", slug: `foreign-${Date.now()}`, deploymentMode: "SELF_HOSTED" });
 await Config.insertMany(["expenses", "reports", "invoices", "customers"].map(moduleKey => ({ businessId: toor._id, moduleKey, state: "ACTIVE" })));
 server = require("../src/app").listen(5011, "127.0.0.1");
 await new Promise(r => server.once("listening", r));
 let token = signAccessToken(owner);
 const request = async (path, { method = "GET", body, entity = toor._id, auth = token, headers = {}, expected = 200 } = {}) => {
   const response = await fetch(`http://127.0.0.1:5011/api${path}`, { method, headers: { ...(auth ? { Authorization: `Bearer ${auth}` } : {}), "x-business-id": String(entity), "Content-Type": "application/json", ...headers }, ...(body ? { body: JSON.stringify(body) } : {}) });
   const json = await response.json();
   assert.equal(response.status, expected, `${method} ${path.replace(/handoffs\/invoice\/.*/, 'handoffs/invoice/[redacted]')}: ${JSON.stringify(json).slice(0,350)}`);
   return json.data;
 };
 const [gh, concurrentGoldhawk] = await Promise.all([request("/business/billing-entities", { method: "POST", body: {} }), request("/business/billing-entities", { method: "POST", body: {} })]);
 assert.equal(String(gh.id), String(concurrentGoldhawk.id));
 assert.equal(String((await request("/business/billing-entities", { method: "POST", body: {} })).id), String(gh.id));
 assert.equal(await Business.countDocuments({ billingParentId: toor._id }), 1);
 assert.equal(await Customer.countDocuments(), 0);
 pass("idempotent Goldhawk provisioning; no customer copies; TOOR ownership unchanged");
 const goldhawkOnly = await User.create({ businessId: gh.id, name: "Goldhawk Only", email: "gh-only@example.test", password: await hashPassword(password), role: "accountant" });
 const goldhawkOnlyToken = signAccessToken(goldhawkOnly);
 await request("/auth/me", { entity: toor._id, auth: goldhawkOnlyToken, expected: 403 });
 assert.equal((await request("/business/billing-entities", { entity: gh.id, auth: goldhawkOnlyToken })).length, 1);
 const listed = await request("/business/billing-entities"); assert.equal(listed.length, 2);
 assert.equal(String((await request("/auth/me", { entity: gh.id })).business.id), String(gh.id));
 await request("/auth/me", { entity: foreign._id, expected: 403 });
 const staffToken = signAccessToken(employee);
 await request("/auth/me", { entity: gh.id, auth: staffToken, expected: 403 });
 await request("/business/billing-entities/members", { method: "PUT", body: { userId: employee._id, businessId: gh.id, role: "accountant" } });
 assert.equal((await request("/auth/me", { entity: gh.id, auth: staffToken })).user.role, "accountant");
 assert.equal((await User.findById(employee._id)).role, "staff");
 await request("/business/billing-entities/members", { method: "PUT", auth: staffToken, body: { userId: employee._id, businessId: foreign._id, role: "admin" }, expected: 403 });
 pass("switching, role isolation, owner-only delegation and unauthorized entity denial");
 const loggedIn = await fetch("http://127.0.0.1:5011/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: owner.email, password }) });
 assert.equal(loggedIn.status, 200);
 const cookie = loggedIn.headers.get("set-cookie").split(";")[0];
 const refreshed = await fetch("http://127.0.0.1:5011/api/auth/refresh", { method: "POST", headers: { Cookie: cookie, "x-business-id": String(gh.id), "Content-Type": "application/json" }, body: "{}" });
 assert.equal(refreshed.status, 200);
 const refreshedSession = (await refreshed.json()).data;
 assert.equal(String(refreshedSession.business.id), String(gh.id));
 assert.equal(refreshedSession.user.role, "admin");
 pass("refresh retains selected entity and its effective role");
 const customer = await request("/customers", { method: "POST", body: { name: "TOOR Test Customer", phone: "9000000101", stateCode: "23", billingAddress: "Original customer address" }, expected: 201 });
 const ghCustomer = await request("/customers", { method: "POST", entity: gh.id, body: { name: "Goldhawk Test Customer", phone: "9000000102" }, expected: 201 });
 const invoiceBody = customerId => ({ customerId, invoiceDate: "2026-10-01", dueDate: "2026-10-10", placeOfSupplyCode: "23", lineItems: [{ productName: "Brokerage service", quantity: 1, rate: 10000, taxRate: 18, hsnSac: "9972" }] });
 const tinv = await request("/invoices", { method: "POST", body: invoiceBody(customer._id), expected: 201 });
 assert.equal(tinv.totalTax, 1800); assert.equal(tinv.grandTotal, 11800); assert.match(tinv.invoiceNumber, /TOOR.*0001/);
 const ginv = await request("/invoices", { method: "POST", entity: gh.id, body: invoiceBody(ghCustomer._id), expected: 201 });
 assert.equal(ginv.totalTax, 0); assert.equal(ginv.grandTotal, 10000); assert.equal(ginv.lineItems[0].taxRate, 0); assert.equal(ginv.gstSnapshot, null); assert.match(ginv.invoiceNumber, /GH.*0001/);
 await request(`/invoices/${tinv._id}`, { entity: gh.id, expected: 404 });
 await request("/invoices", { method: "POST", entity: gh.id, body: invoiceBody(customer._id), expected: 404 });
 assert.equal((await Business.findById(toor._id)).invoiceNumbering.nextSequence, 2);
 assert.equal((await Business.findById(gh.id)).invoiceNumbering.nextSequence, 2);
 pass("TOOR GST 1800; Goldhawk GST 0 despite submitted 18%; separate numbering and invoice/customer isolation");
 const paid = await request("/payments", { method: "POST", body: { direction: "RECEIVED", amount: 4000, customerId: customer._id, paymentMethod: "CASH", idempotencyKey: "phase1-partial" }, expected: 201 });
 await request(`/payments/${paid._id}/allocate`, { method: "POST", body: { invoiceId: tinv._id, allocatedAmount: 4000 }, expected: 201 });
 const updated = await request(`/invoices/${tinv._id}`); assert.equal(updated.balanceDue, 7800); assert.equal(updated.paymentStatus, "partial");
 await request(`/payments/${paid._id}`, { entity: gh.id, expected: 404 });
 const exp = await request("/expenses", { method: "POST", body: { description: "Local test expense", amountBeforeTax: 100, category: "Miscellaneous", paymentStatus: "UNPAID" }, expected: 201 });
 await request(`/expenses/${exp._id}`, { entity: gh.id, expected: 404 });
 assert.equal((await request("/reports/summary", { entity: gh.id })).collectionSummary.totalSales, 10000);
 pass("partial payment and scoped payments/expenses/reports");
 const frozen = await Invoice.findById(tinv._id).lean();
 const legacyId = new mongoose.Types.ObjectId();
 await Invoice.collection.insertOne({ ...frozen, _id: legacyId, invoiceNumber: "LEGACY-1", sellerSnapshot: null });
 await request("/business/setup", { method: "PUT", body: { name: "TOOR edited profile", industry: "Real Estate", address: "New seller address", gstEnabled: true, gstConfigurationGstin: "23CGZPB7175E1Z5", gstStateCode: "23", invoicePrefix: "TOOR", bankName: "Changed bank", bankAccountNumber: "changed" } });
 const currentBusiness = await Business.findById(toor._id);
 const same = await Invoice.findById(tinv._id).lean();
 assert.equal(same.sellerSnapshot.name, "The Office On Rent"); assert.equal(same.sellerSnapshot.bankDetails.bankName, "Test bank");
 const legacy = await Invoice.findById(legacyId).lean(); assert.equal(legacy.sellerSnapshot.name, "The Office On Rent");
 const pdf = JSON.stringify(buildInvoicePdfDefinition({ invoice: same, business: currentBusiness })); assert.ok(pdf.includes("The Office On Rent")); assert.ok(!pdf.includes("TOOR edited profile")); assert.ok(pdf.includes("Test bank"));
 await request("/business/setup", { method: "PUT", entity: gh.id, body: { name: "Goldhawk Infrabulls Pvt. Ltd.", industry: "Real Estate", gstEnabled: true, gstConfigurationGstin: "23CGZPB7175E1Z5", gstStateCode: "23", taxRate: 18, invoicePrefix: "GH" } });
 assert.equal((await Business.findById(gh.id)).gstConfiguration.enabled, false);
 pass("immutable seller/PDF bank snapshot, idempotent legacy freeze and server-enforced Goldhawk settings");
 const credential = await request("/integrations/credentials", { method: "POST", body: { name: "Isolated CRM regression", source: "THE_OFFICE_ON_RENT_CRM" }, expected: 201 });
 const sync = async externalId => request("/integrations/customers/upsert", { method: "POST", auth: "", headers: { "X-Billstack-Api-Key": credential.apiKey }, body: { externalId, source: "THE_OFFICE_ON_RENT_CRM", name: "CRM Regression Customer", phone: "9000000199" }, expected: 201 });
 const synced = await sync("toor:test:lead:closed");
 const again = await request("/integrations/customers/upsert", { method: "POST", auth: "", headers: { "X-Billstack-Api-Key": credential.apiKey }, body: { externalId: "toor:test:lead:closed", source: "THE_OFFICE_ON_RENT_CRM", name: "CRM Regression Customer", phone: "9000000199" } });
 assert.equal(String(again.customer._id), String(synced.customer._id));
 const handoff = async () => request("/integrations/handoffs/invoice", { method: "POST", auth: "", headers: { "X-Billstack-Api-Key": credential.apiKey }, body: { customerId: synced.customer._id }, expected: 201 });
 const link = await handoff(); const ht = new URL(link.handoffUrl).searchParams.get("token");
 const context = await request(`/integrations/handoffs/invoice/${ht}`, { entity: gh.id });
 assert.equal(String(context.session.business.id), String(toor._id)); assert.equal(String(context.customer._id), String(synced.customer._id));
 await request(`/integrations/handoffs/invoice/${ht}`, { entity: gh.id, expected: 404 });
 pass("CRM customer retry mapping, handoff back to TOOR from Goldhawk and token replay rejection");
 if (process.env.BILLSTACK_PHASE1_UI) {
   const { chromium } = require(process.env.BILLSTACK_PLAYWRIGHT_PATH || "playwright");
   browser = await chromium.launch({ channel: "msedge", headless: true });
   const errors = [];
   const context = await browser.newContext(); const page = await context.newPage(); page.on("pageerror", e => errors.push(e.message));
   const login = async () => {
     await page.locator('input[name="email"]').fill(owner.email);
     await page.locator('input[name="password"]').fill(password);
     await page.locator('button[type="submit"]').click();
   };
   await page.goto(`${process.env.CLIENT_URL}/login`); await login();
   await page.waitForURL("**/dashboard");
   const switcher = page.getByLabel("Active billing company", { exact: true });
   await switcher.selectOption(String(gh.id));
   await page.waitForFunction(id => JSON.parse(localStorage.getItem("billstack-auth")).business.id === id, String(gh.id));
   await page.waitForLoadState("networkidle");
   assert.ok((await page.locator("header").first().innerText()).includes("Goldhawk"));
   for (const path of ["customers", "invoices", "reports", "expenses"]) { await page.goto(`${process.env.CLIENT_URL}/dashboard/${path}`); await page.waitForLoadState("networkidle"); assert.ok(!page.url().includes("login")); }
   await page.goto(`${process.env.CLIENT_URL}/dashboard/invoices?action=create`);
   await page.locator('select[name="customerId"]').selectOption(String(ghCustomer._id));
   await page.getByPlaceholder("Type item or service").fill("Residential brokerage UI");
   await page.getByLabel("Rate", { exact: true }).fill("2500");
   assert.equal(await page.getByLabel("GST %", { exact: true }).inputValue(), "0");
   assert.equal(await page.getByLabel("GST %", { exact: true }).isDisabled(), true);
   const issuedResponse = page.waitForResponse(r => r.url().endsWith("/api/invoices") && r.request().method() === "POST");
   await page.getByRole("button", { name: "Issue Invoice", exact: true }).click();
   const issued = await issuedResponse; assert.equal(issued.status(), 201);
   const issuedBody = (await issued.json()).data; assert.equal(issuedBody.totalTax, 0); assert.equal(issuedBody.grandTotal, 2500);
   pass("REAL BROWSER Goldhawk invoice issue with locked zero GST");
   let consumes = 0;
   page.on("request", r => { if (r.url().includes("/api/integrations/handoffs/invoice/")) consumes++; });
   const browserLink = await handoff();
   await page.goto(browserLink.handoffUrl); await page.waitForURL("**/dashboard/invoices?action=create");
   await page.waitForFunction(id => document.querySelector('select[name="customerId"]')?.value === id, String(synced.customer._id));
   assert.equal(await page.locator('select[name="customerId"]').inputValue(), String(synced.customer._id));
   assert.ok((await page.locator("header").first().innerText()).includes("TOOR edited profile"));
   await page.waitForLoadState("networkidle");
   assert.equal(consumes, 1, "Cross-entity handoff consumes once");
   await page.getByPlaceholder("Type item or service").fill("Commercial brokerage UI");
   await page.getByLabel("Rate", { exact: true }).fill("5000");
   await page.getByLabel("GST %", { exact: true }).fill("18");
   await page.locator('select[name="placeOfSupplyCode"]').selectOption("23");
   await page.getByLabel("HSN/SAC", { exact: true }).fill("9972");
   const toorIssuedResponse = page.waitForResponse(r => r.url().endsWith("/api/invoices") && r.request().method() === "POST");
   await page.getByRole("button", { name: "Issue Invoice", exact: true }).click();
   const toorIssued = await toorIssuedResponse; assert.equal(toorIssued.status(), 201);
   assert.equal((await toorIssued.json()).data.totalTax, 900);
   pass("REAL BROWSER TOOR GST invoice issue after CRM handoff");
   await context.close();
   const fresh = await browser.newContext(); const freshPage = await fresh.newPage(); freshPage.on("pageerror", e => errors.push(e.message));
   const loggedOutLink = await handoff(); await freshPage.goto(loggedOutLink.handoffUrl); await freshPage.waitForURL("**/login");
   await freshPage.locator('input[name="email"]').fill(owner.email); await freshPage.locator('input[name="password"]').fill(password); await freshPage.locator('button[type="submit"]').click();
   await freshPage.waitForURL("**/dashboard/invoices?action=create");
   await freshPage.waitForFunction(id => document.querySelector('select[name="customerId"]')?.value === id, String(synced.customer._id));
   assert.deepEqual(errors, []);
   await fresh.close();
   pass("REAL BROWSER login, entity switch without logout, pages, logged-in and logged-out CRM handoff, correct customer, no runtime errors");
 }
 await request("/business/billing-entities/members", { method: "PUT", body: { userId: employee._id, businessId: gh.id, remove: true } });
 await request("/auth/me", { entity: gh.id, auth: staffToken, expected: 403 });
 pass("membership revocation takes effect on the next request");
 console.log("PHASE1 E2E COMPLETE (isolated test DB retained; no existing DB modified)");
})().catch(e => { console.error(e.stack); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); if (server) await new Promise(r => server.close(r)); await mongoose.disconnect(); });
